[package]
name = "runner"
version = "0.1.0"
edition = "2021"


[dependencies]
sbc_algorithm = { path = "../." }
fastcdc = "3.1.0"
chunkfs = { git = "https://github.com/Piletskii-Oleg/chunkfs.git", branch = "SBC-FBC-support" }
